language: ruby

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false

rvm:
  - 2.2.4

bundler_args: --without development --deployment --jobs=3 --retry=3

cache: bundler

before_script:
  - bundle exec rake db:migrate --trace

script: bundle exec rake
